### ISSUE TITLE
Can you update this to 1.16.5

### ISSUE THREAD

**Issue by RehanPlayz** [DichuuCraft/SReplay#1]
The Title Says it all

**Comment by 4o3F** [comment]
@RehanPlayz I've updated it on [my fork](https://github.com/ExusiaiMoe/SReplay), though not fully tested yet

**Comment by Hadron67** [comment]
@RehanPlayz Sorry for the delay, I have finally done this. The release isn't published yet but I've set up the CI so you can download the development build.
