### ISSUE TITLE
1.16.5 srplay cannot start normally under windows

### ISSUE THREAD

**Issue by frankiebegonia** [DichuuCraft/SReplay#2]
The Title Says it a
log document
[2021-10-04-2.log.gz](https://github.com/DichuuCraft/SReplay/files/7275222/2021-10-04-2.log.gz)
ll

**Comment by 111inhistory** [comment]
It seems that it is compatible with 1.16.2.I hope authors can continue to update,then I don't need to use PCRC to capture.

**Comment by Hadron67** [comment]
My mistake, i forgot to bump minecraft version in `fabric.mod.json` from 1.16.2 to 1.16.5. I have filed a [new release](https://github.com/DichuuCraft/SReplay/releases/tag/v0.3.1) which should work without issue. Please reopen this if the issue still exists.
